// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP3hzCHJ_0_VeHsBk8NQLEO9Xgceiv6hc',
    appId: '1:249421913253:web:3cfdada03b0c195fe4c14c',
    messagingSenderId: '249421913253',
    projectId: 'aidocauth',
    authDomain: 'aidocauth.firebaseapp.com',
    storageBucket: 'aidocauth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5KFm5BDICrQyUgxEXFZ67hCE7DEEp_sE',
    appId: '1:249421913253:android:90ea3116ba5efc62e4c14c',
    messagingSenderId: '249421913253',
    projectId: 'aidocauth',
    storageBucket: 'aidocauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcPWCB6sCkjKHRqFsF8oL3vP6Ut3cN4H0',
    appId: '1:249421913253:ios:88318f726e1a5d9de4c14c',
    messagingSenderId: '249421913253',
    projectId: 'aidocauth',
    storageBucket: 'aidocauth.firebasestorage.app',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcPWCB6sCkjKHRqFsF8oL3vP6Ut3cN4H0',
    appId: '1:249421913253:ios:88318f726e1a5d9de4c14c',
    messagingSenderId: '249421913253',
    projectId: 'aidocauth',
    storageBucket: 'aidocauth.firebasestorage.app',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP3hzCHJ_0_VeHsBk8NQLEO9Xgceiv6hc',
    appId: '1:249421913253:web:789485cc5d12dcc7e4c14c',
    messagingSenderId: '249421913253',
    projectId: 'aidocauth',
    authDomain: 'aidocauth.firebaseapp.com',
    storageBucket: 'aidocauth.firebasestorage.app',
  );
}
